Factura:
  connection: doctrine
  tableName: factura
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    ts:
      type: timestamp(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    name:
      type: string(80)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    ruc:
      type: string(110)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    pedido_id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    sub_total:
      type: 'decimal(8, 2)'
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    iva:
      type: 'decimal(8, 2)'
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    total:
      type: 'decimal(8, 2)'
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
Ingredientes:
  connection: doctrine
  tableName: ingredientes
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    name:
      type: string(30)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    owner_prod_id:
      type: string(30)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    state:
      type: string(1)
      fixed: true
      unsigned: false
      primary: false
      default: F
      notnull: false
      autoincrement: false
    fec_upd:
      type: timestamp(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
Mesa:
  connection: doctrine
  tableName: mesa
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    label:
      type: string(40)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
  relations:
    Pedidos:
      local: id
      foreign: mesa_id
      type: many
Notificacion:
  connection: doctrine
  tableName: notificacion
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    fec_reg:
      type: timestamp(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    text:
      type: string(250)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    pedido_id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    seen:
      type: integer(1)
      fixed: false
      unsigned: false
      primary: false
      default: '0'
      notnull: true
      autoincrement: false
    state:
      type: integer(1)
      fixed: false
      unsigned: false
      primary: false
      default: '0'
      notnull: true
      autoincrement: false
Pedidos:
  connection: doctrine
  tableName: pedidos
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    precio:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    fec_reg:
      type: timestamp(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    fec_can:
      type: timestamp(25)
      fixed: false
      unsigned: false
      primary: false
      default: '0000-00-00 00:00:00'
      notnull: true
      autoincrement: false
    mesa_id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    estado:
      type: integer(1)
      fixed: false
      unsigned: false
      primary: false
      default: '0'
      notnull: true
      autoincrement: false
  relations:
    Mesa:
      local: mesa_id
      foreign: id
      type: one
    PedidosDetalle:
      local: id
      foreign: pedido_id
      type: many
PedidosDetalle:
  connection: doctrine
  tableName: pedidos_detalle
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    pedido_id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    item:
      type: string(40)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    sub_producto_id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
  relations:
    Pedidos:
      local: pedido_id
      foreign: id
      type: one
Producto:
  connection: doctrine
  tableName: producto
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    name:
      type: string(30)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    state:
      type: integer(1)
      fixed: false
      unsigned: false
      primary: false
      default: '0'
      notnull: false
      autoincrement: false
  relations:
    ProductoImages:
      local: id
      foreign: product_id
      type: many
    SubProducto:
      local: id
      foreign: producto_id
      type: many
ProductoImages:
  connection: doctrine
  tableName: producto_images
  columns:
    product_id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    path_img:
      type: string(100)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
  relations:
    Producto:
      local: product_id
      foreign: id
      type: one
SubProducto:
  connection: doctrine
  tableName: sub_producto
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    name:
      type: string(40)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    producto_id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    precio:
      type: 'decimal(12, 2)'
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    fec_updated:
      type: timestamp(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    state:
      type: integer(1)
      fixed: false
      unsigned: false
      primary: false
      default: '0'
      notnull: false
      autoincrement: false
  relations:
    Producto:
      local: producto_id
      foreign: id
      type: one
SubProductoIngredientes:
  connection: doctrine
  tableName: sub_producto_ingredientes
  columns:
    sub_producto_id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: false
    ingredientes_id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: false
Usuario:
  connection: doctrine
  tableName: usuario
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    username:
      type: string(40)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    password:
      type: string(60)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
