<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2013/11/25 02:25:24

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=comandos',
  'username' => 'root',
  'password' => 'paraguay',
  'name' => 'doctrine',
)),);
