<?php
// auto-generated by sfViewConfigHandler
// date: 2013/11/25 02:25:33
$response = $this->context->getResponse();


  $templateName = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_template', $this->actionName);
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());



  if (null !== $layout = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_layout'))
  {
    $this->setDecoratorTemplate(false === $layout ? false : $layout.$this->getExtension());
  }
  else if (null === $this->getDecoratorTemplate() && !$this->context->getRequest()->isXmlHttpRequest())
  {
    $this->setDecoratorTemplate('' == 'layout' ? false : 'layout'.$this->getExtension());
  }
  $response->addHttpMeta('content-type', 'text/html', false);

  $response->addStylesheet('imports.css', '', array ());
  $response->addJavascript('jquery-1.7.2.min.js', '', array ());
  $response->addJavascript('main.js', '', array ());
  $response->addJavascript('plugins.js', '', array ());
  $response->addJavascript('modernizr-2.0.6.min.js', '', array ());


