<?php
// auto-generated by sfSecurityConfigHandler
// date: 2013/11/25 02:25:24
$this->security = array (
  'index' => 
  array (
    'is_secure' => false,
  ),
  'all' => 
  array (
    'is_secure' => false,
  ),
);
