<?php

/**
 * FacturaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FacturaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FacturaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Factura');
    }
    public function insertRow($datos_factura)
    {
        $sub_total=$datos_factura['sub_total'];
        $iva=$datos_factura['iva'];
        $name=$datos_factura['nombre'];
        $ruc=$datos_factura['ruc'];
        $pedido_id=$datos_factura['pedido_id'];
        $total=$sub_total+$iva;
          $connection = Doctrine_Manager::getInstance()->getCurrentConnection()->getDbh();
        $query = "INSERT INTO factura (pedido_id, name,ruc,sub_total,iva,total) VALUES( ? , ?,?,?,?,? );";
        $statement = $connection->prepare($query);
        $statement->bindValue(1, $pedido_id);
        $statement->bindValue(2, $name);
        $statement->bindValue(3, $ruc);
        $statement->bindValue(4, $sub_total);
        $statement->bindValue(5, $iva);
        $statement->bindValue(6,$total);
        $statement->execute();    

        
                $sql=' select last_insert_id() as id';
        $statmet=$connection->prepare($sql);
        $statmet->execute();
        $row=$statmet->fetch();
        $last_id=$row['id'];
        return $last_id;
        
        
        
    }
}