<?php

/**
 * Factura
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    comandas
 * @subpackage model
 * @author     Kiquetal
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Factura extends BaseFactura
{
}
