<?php

/**
 * IngredientesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class IngredientesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object IngredientesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Ingredientes');
    }
    public function insertRawRow($params)
    {
 
        echo 'ingredeintes insert!!';
        $param=$params['ingredientes'];
        $nom=$param['name'];
        $prod=@$param['producto_id']?$param['producto_id']:'';
        $an=  implode(',', (array)$prod);
        $connection = Doctrine_Manager::getInstance()->getCurrentConnection()->getDbh();
        $query = "INSERT INTO ingredientes (name, owner_prod_id) VALUES( ? , ? );";
        $statement = $connection->prepare($query);
        $statement->bindValue(1, $nom);
        $statement->bindValue(2, $an);
        $statement->execute();    

        print_r("antes de obtener el maximo ingredientes");
        $query2=" Select max(id) as id from ingredientes";
        $connection2=Doctrine_Manager::getInstance()->getCurrentConnection()->getDbh();
        $stm=$connection2->prepare($query2);
        
        $stm->execute();
        $objec=$stm->fetch();
        print $objec;
        return $objec['id'];
        
    }
    
    public function updateRow($params)
    {
        echo $params;
        $prod_id=$params['owner_prod_id'];
       $connection=$connection = Doctrine_Manager::getInstance()->getCurrentConnection()->getDbh();
       $new_prod_id=  implode(",", $prod_id);
   
       $id=$params['id'];
       $name=$params['ingrediente']['nombre'];
       $query=" Replace into ingredientes (id,name,owner_prod_id) VALUES (?,?,?);";
       
       $statment=$connection->prepare($query);
       $statment->bindValue(1, $id);
       $statment->bindValue(2, $name);
       $statment->bindValue(3,$new_prod_id);
       $statment->execute();  
        
    }
    public function deleteIngre($id)
    {
        
        $query=" Update ingredientes set state=1 where id= ?";
        $connection=Doctrine_Manager::getInstance()->getCurrentConnection()->getDbh();
        $stm=$connection->prepare($query);
        $stm->bindValue(1,$id);
        $stm->execute();
    }
    public function checkState($id)
    {
        $query=" Select state from ingredientes where id = ?";
        $connection=Doctrine_Manager::getInstance()->getCurrentConnection()->getDbh();
        $stm=$connection->prepare($query);
        $stm->bindValue(1,$id);
        $stm->execute();
        $objec=$stm->fetch();
        $state=$objec['state'];
        print $state;
        return $state;
        
    }
}