<?php

/**
 * MesaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MesaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MesaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Mesa');
    }
}