<?php

/**
 * PedidosTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PedidosTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PedidosTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Pedidos');
    }
    public function updatePrecioPedido($precio,$id)
    {
        
       $connection = Doctrine_Manager::getInstance()->getCurrentConnection()->getDbh();
       $query=" UPDATE pedidos set precio=? where id=?;";
              $statment=$connection->prepare($query);
       $statment->bindValue(1, $precio);
       $statment->bindValue(2, $id);
       $statment->execute();  
       
        
    }
    
    public function updateStatus($pedido_id,$state)
    {
        $d=new \DateTime();
        $d->setTimestamp(time());
       $connection = Doctrine_Manager::getInstance()->getCurrentConnection()->getDbh();
       $query=" Update pedidos set estado=?,fec_can=? where id=?";
       $statment=$connection->prepare($query);
       $statment->bindValue(1, $state);
       $statment->bindValue(2,  $d->format(\DateTime::ISO8601));
       $statment->bindValue(3, $pedido_id);
      
     return  $statment->execute();  
       
    }
   
    
    
    public function insertPedido()
    {
        
       $e='0'; 
       $connection = Doctrine_Manager::getInstance()->getCurrentConnection()->getDbh();
       $query=" INSERT into pedidos (estado,mesa_id) VALUES (?,?);";
       
       $statment=$connection->prepare($query);
       $statment->bindValue(1, $e);
       $statment->bindValue(2, 1);

       $statment->execute();  
       
       
        $query=" Select last_insert_id() as seq";
          $stm=$connection->prepare($query);
       
        $stm->execute();
        $objec=$stm->fetch();
        
        $seq=$objec['seq'];
        
        return $seq;
       
        
    }
        
        
    
}