<?php

/**
 * ProductoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProductoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProductoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Producto');
    }
    
    public function insertProducto($arr)
    {
        $name=$arr['name'];

        $connection = Doctrine_Manager::getInstance()->getCurrentConnection()->getDbh();
        $sql=' INSERT INTO producto (name) VALUES (?)';
        $statmet=$connection->prepare($sql);
        $statmet->bindValue(1,$name);
        $statmet->execute();
        $sql=' select last_insert_id() as id';
        $statmet=$connection->prepare($sql);
        $statmet->execute();
        $row=$statmet->fetch();
        $last_id=$row['id'];
  
        return $last_id;
    }
    public function updateProduct($datos)
    {
        
        $name=$datos['name'];
        $id=$datos['id'];
        $connection = Doctrine_Manager::getInstance()->getCurrentConnection()->getDbh();
        $sql=' UPDATE producto SET name= ? where id=? ';
        $statmet=$connection->prepare($sql);
        $statmet->bindValue(1,$name);
        $statmet->bindValue(2,$id);
        $statmet->execute();
        
    }
    
    public function getAvailable()
    {
        

        return  Doctrine_Core::getTable("Producto")->createQuery('p')
                  ->where('p.state=?',0)
                  ->execute();
        
    }
    public function changeStatus($status,$id)
    {
        
        
        $connection = Doctrine_Manager::getInstance()->getCurrentConnection()->getDbh();
        $sql=' UPDATE producto SET state= ? where id=? ';
        $statmet=$connection->prepare($sql);
        $statmet->bindValue(1,$status);
        $statmet->bindValue(2,$id);
        $statmet->execute();
	
	$connection = Doctrine_Manager::getInstance()->getCurrentConnection()->getDbh();
        $sql=' UPDATE sub_producto SET state= ? where producto_id=? ';
        $statmet=$connection->prepare($sql);
        $statmet->bindValue(1,$status);
        $statmet->bindValue(2,$id);
        $statmet->execute();
	
	
        
        
    }
}