<?php

/**
 * ProductoImagesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProductoImagesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProductoImagesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProductoImages');
    }
    public function insertImageProduct($datos)
    {
        
        $producto_id=$datos['product_id'];
        $path=$datos['path'];
        $connection = Doctrine_Manager::getInstance()->getCurrentConnection()->getDbh();
        $sql=' INSERT INTO producto_images (product_id,path_img) VALUES (?,?)';
        $statmet=$connection->prepare($sql);
        $statmet->bindValue(1,$producto_id);
        $statmet->bindValue(2,$path);
        $statmet->execute();
   
        
    }
    
    public function replaceImageProduct($datos)
    {
        
        $producto_id=  intval($datos['product_id']);
        $path=$datos['path'];
        $connection = Doctrine_Manager::getInstance()->getCurrentConnection()->getDbh();
        $sql=' UPDATE producto_images set path_img = ?
                                   WHERE product_id = ? ';
        $statmet=$connection->prepare($sql);
        $statmet->bindValue(1,$path);
        $statmet->bindValue(2,$producto_id);
        $statmet->execute();
   
        
    }
    
}