<?php

/**
 * SubProductoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SubProductoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SubProductoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SubProducto');
    }
    
    public function removeSubProduct($params)
    {
        
        $sub_prod=$params['sub_producto_id'];
   $connection = Doctrine_Manager::getInstance()->getCurrentConnection()->getDbh();
     
   $sql=' UPDATE sub_producto set state=1 where id=?';
   $statmet=$connection->prepare($sql);
   $statmet->bindValue(1,$sub_prod);

   $statmet->execute();
        
        
        
        
        
    }
    
    public function insert($params)
   {
        
   $array=$params['sub_producto'];       
   $nom=$array['name'];
   $prec=$params['precio'];
   $prod=$array['producto_id'];
   $ingre_array=  @$array['ingredientes_id']?$array['ingredientes_id']:array();
   $array_new_ingre=$params['new_ingredientes'];
   
   
   
   $connection = Doctrine_Manager::getInstance()->getCurrentConnection()->getDbh();
     
   $sql=' INSERT INTO sub_producto (name,producto_id,precio) VALUES (?,?,?)';
   $statmet=$connection->prepare($sql);
   $statmet->bindValue(1,$nom);
   $statmet->bindValue(2,$prod);
   $statmet->bindValue(3,$prec);
   $statmet->execute();
   
      
   $sql=' select max(id) as id from sub_producto';
   $statmet=$connection->prepare($sql);
   $statmet->execute();
   $row=$statmet->fetch();
   $sub_producto_id=$row['id'];
   /*
    * 
    *    $param=$params['ingredientes'];
        $prod=@$param['producto_id']?$param['producto_id']:'';
        $an=  implode(',', (array)$prod);
        $connection = Doctrine_Manager::getInstance()->getCurrentConnection()->getDbh();
        $query = "INSERT INTO ingredientes (name, owner_prod_id) VALUES( ? , ? );";
        $statement = $connection->prepare($query);
        $statement->bindValue(1, $param['name']);
        $statement->bindValue(2, $an);
        $statement->execute();    
     
    * 
    */
     $array_ingres=array();
        foreach ($array_new_ingre as $k)
        {
            $ingre=array('ingredientes'=>array('name'=>$k,'producto_id'=>$prod));
            
            if (strlen($k)>1)
            {
             $array_ingres [] =Doctrine_Core::getTable('Ingredientes')->insertRawRow($ingre);
            }
             
        }
      
        echo 'SUB PRODUCTO INGREDIENTES';
        
         Doctrine_Core::getTable('SubProductoIngredientes')->insertRawRow(array(
                                                            'sub_producto_id'=>$sub_producto_id,
                                                             'ingredientes_id'=> array_merge($ingre_array, $array_ingres)));
       
    }            
            
}
