<?php

/**
 * SubProductoIngredientesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SubProductoIngredientesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SubProductoIngredientesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SubProductoIngredientes');
    }
    public function insertRawRow($params)
    {
        $product=$params['sub_producto_id'];
        $array_ingre=(array) $params['ingredientes_id'];
        print_r($array_ingre);
        foreach ($array_ingre as $ingre)
        {
           $subPrdo=new SubProductoIngredientes();
           $subPrdo->setIngredientesId($ingre);
           $subPrdo->setSubProductoId($product);
           $subPrdo->save();
          
        }
        
        
        
    }
}