<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('SubProducto', 'doctrine');

/**
 * BaseSubProducto
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property integer $producto_id
 * @property decimal $precio
 * @property timestamp $fec_updated
 * @property integer $state
 * @property Producto $Producto
 * 
 * @method integer     getId()          Returns the current record's "id" value
 * @method string      getName()        Returns the current record's "name" value
 * @method integer     getProductoId()  Returns the current record's "producto_id" value
 * @method decimal     getPrecio()      Returns the current record's "precio" value
 * @method timestamp   getFecUpdated()  Returns the current record's "fec_updated" value
 * @method integer     getState()       Returns the current record's "state" value
 * @method Producto    getProducto()    Returns the current record's "Producto" value
 * @method SubProducto setId()          Sets the current record's "id" value
 * @method SubProducto setName()        Sets the current record's "name" value
 * @method SubProducto setProductoId()  Sets the current record's "producto_id" value
 * @method SubProducto setPrecio()      Sets the current record's "precio" value
 * @method SubProducto setFecUpdated()  Sets the current record's "fec_updated" value
 * @method SubProducto setState()       Sets the current record's "state" value
 * @method SubProducto setProducto()    Sets the current record's "Producto" value
 * 
 * @package    comandas
 * @subpackage model
 * @author     Kiquetal
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSubProducto extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sub_producto');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 40, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 40,
             ));
        $this->hasColumn('producto_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('precio', 'decimal', 12, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 12,
             'scale' => '2',
             ));
        $this->hasColumn('fec_updated', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('state', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Producto', array(
             'local' => 'producto_id',
             'foreign' => 'id'));
    }
}