<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('SubProductoIngredientes', 'doctrine');

/**
 * BaseSubProductoIngredientes
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $sub_producto_id
 * @property integer $ingredientes_id
 * 
 * @method integer                 getSubProductoId()   Returns the current record's "sub_producto_id" value
 * @method integer                 getIngredientesId()  Returns the current record's "ingredientes_id" value
 * @method SubProductoIngredientes setSubProductoId()   Sets the current record's "sub_producto_id" value
 * @method SubProductoIngredientes setIngredientesId()  Sets the current record's "ingredientes_id" value
 * 
 * @package    comandas
 * @subpackage model
 * @author     Kiquetal
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSubProductoIngredientes extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sub_producto_ingredientes');
        $this->hasColumn('sub_producto_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('ingredientes_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}