<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Pedidos', 'doctrine');

/**
 * BasePedidos
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $precio
 * @property timestamp $fec_reg
 * @property timestamp $fec_can
 * @property integer $mesa_id
 * @property integer $estado
 * @property Mesa $Mesa
 * @property Doctrine_Collection $PedidosDetalle
 * 
 * @method integer             getId()             Returns the current record's "id" value
 * @method integer             getPrecio()         Returns the current record's "precio" value
 * @method timestamp           getFecReg()         Returns the current record's "fec_reg" value
 * @method timestamp           getFecCan()         Returns the current record's "fec_can" value
 * @method integer             getMesaId()         Returns the current record's "mesa_id" value
 * @method integer             getEstado()         Returns the current record's "estado" value
 * @method Mesa                getMesa()           Returns the current record's "Mesa" value
 * @method Doctrine_Collection getPedidosDetalle() Returns the current record's "PedidosDetalle" collection
 * @method Pedidos             setId()             Sets the current record's "id" value
 * @method Pedidos             setPrecio()         Sets the current record's "precio" value
 * @method Pedidos             setFecReg()         Sets the current record's "fec_reg" value
 * @method Pedidos             setFecCan()         Sets the current record's "fec_can" value
 * @method Pedidos             setMesaId()         Sets the current record's "mesa_id" value
 * @method Pedidos             setEstado()         Sets the current record's "estado" value
 * @method Pedidos             setMesa()           Sets the current record's "Mesa" value
 * @method Pedidos             setPedidosDetalle() Sets the current record's "PedidosDetalle" collection
 * 
 * @package    comandas
 * @subpackage model
 * @author     Kiquetal
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePedidos extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('pedidos');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('precio', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('fec_reg', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('fec_can', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0000-00-00 00:00:00',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('mesa_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('estado', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Mesa', array(
             'local' => 'mesa_id',
             'foreign' => 'id'));

        $this->hasMany('PedidosDetalle', array(
             'local' => 'id',
             'foreign' => 'pedido_id'));
    }
}