<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Mesa', 'doctrine');

/**
 * BaseMesa
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $label
 * @property Doctrine_Collection $Pedidos
 * 
 * @method integer             getId()      Returns the current record's "id" value
 * @method string              getLabel()   Returns the current record's "label" value
 * @method Doctrine_Collection getPedidos() Returns the current record's "Pedidos" collection
 * @method Mesa                setId()      Sets the current record's "id" value
 * @method Mesa                setLabel()   Sets the current record's "label" value
 * @method Mesa                setPedidos() Sets the current record's "Pedidos" collection
 * 
 * @package    comandas
 * @subpackage model
 * @author     Kiquetal
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMesa extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('mesa');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('label', 'string', 40, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 40,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Pedidos', array(
             'local' => 'id',
             'foreign' => 'mesa_id'));
    }
}