<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('PedidosDetalle', 'doctrine');

/**
 * BasePedidosDetalle
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $pedido_id
 * @property string $item
 * @property integer $sub_producto_id
 * @property Pedidos $Pedidos
 * 
 * @method integer        getId()              Returns the current record's "id" value
 * @method integer        getPedidoId()        Returns the current record's "pedido_id" value
 * @method string         getItem()            Returns the current record's "item" value
 * @method integer        getSubProductoId()   Returns the current record's "sub_producto_id" value
 * @method Pedidos        getPedidos()         Returns the current record's "Pedidos" value
 * @method PedidosDetalle setId()              Sets the current record's "id" value
 * @method PedidosDetalle setPedidoId()        Sets the current record's "pedido_id" value
 * @method PedidosDetalle setItem()            Sets the current record's "item" value
 * @method PedidosDetalle setSubProductoId()   Sets the current record's "sub_producto_id" value
 * @method PedidosDetalle setPedidos()         Sets the current record's "Pedidos" value
 * 
 * @package    comandas
 * @subpackage model
 * @author     Kiquetal
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePedidosDetalle extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('pedidos_detalle');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('pedido_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('item', 'string', 40, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 40,
             ));
        $this->hasColumn('sub_producto_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Pedidos', array(
             'local' => 'pedido_id',
             'foreign' => 'id'));
    }
}