<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Notificacion', 'doctrine');

/**
 * BaseNotificacion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property timestamp $fec_reg
 * @property string $text
 * @property integer $pedido_id
 * @property integer $seen
 * @property integer $state
 * 
 * @method integer      getId()        Returns the current record's "id" value
 * @method timestamp    getFecReg()    Returns the current record's "fec_reg" value
 * @method string       getText()      Returns the current record's "text" value
 * @method integer      getPedidoId()  Returns the current record's "pedido_id" value
 * @method integer      getSeen()      Returns the current record's "seen" value
 * @method integer      getState()     Returns the current record's "state" value
 * @method Notificacion setId()        Sets the current record's "id" value
 * @method Notificacion setFecReg()    Sets the current record's "fec_reg" value
 * @method Notificacion setText()      Sets the current record's "text" value
 * @method Notificacion setPedidoId()  Sets the current record's "pedido_id" value
 * @method Notificacion setSeen()      Sets the current record's "seen" value
 * @method Notificacion setState()     Sets the current record's "state" value
 * 
 * @package    comandas
 * @subpackage model
 * @author     Kiquetal
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseNotificacion extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('notificacion');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('fec_reg', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('text', 'string', 250, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 250,
             ));
        $this->hasColumn('pedido_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('seen', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('state', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}